name: Npm Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - .github/workflows/npm-publish.yml
  workflow_dispatch:

jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-publish.yml@main
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    with:
      build-command: "npm run build"
      test-command: "echo 'Tests are temporarily disabled'"
      should-generate-documentation: true
      generate-documentation-command: |
        chmod +x ./dist/cli/generate-help-of-cli-apps-in-markdown-format.js
        cli_help=$(node ./dist/cli/generate-help-of-cli-apps-in-markdown-format.js --cli-app-file-paths $(find ./dist/cli/*.js) --root-header-level 2)
        pattern="(<!-- CLI_HELP_START -->)[\\S\\s]*(<!-- CLI_HELP_END -->)"
        replacement=$'$1\n'"${cli_help}"$'\n$2'
        npx --yes replace "$pattern" "$replacement" README.md

        cli_usage_ways=$(npx --yes @freephoenix888/generate-usage-ways-of-npm-cli-apps-in-markdown-format  --root-header-level 2)
        pattern="(<!-- CLI_USAGE_WAYS_START -->)[\\S\\s]*(<!-- CLI_USAGE_WAYS_END -->)"
        replacement=$'$1\n'"${cli_usage_ways}"$'\n$2'
        npx --yes replace "$pattern" "$replacement" README.md

        table_of_contents=$(npx markdown-toc README.md)
        pattern="(<!-- TABLE_OF_CONTENTS_START -->)[\\S\\s]*(<!-- TABLE_OF_CONTENTS_END -->)"
        replacement=$'$1\n'"${table_of_contents}"$'\n$2'
        npx replace "$pattern" "$replacement" README.md

        git config --global user.name 'FreePhoenix888'
        git config --global user.email 'freephoenix888@gmail.com'

        git add README.md
        if git diff --staged --quiet
        then
          echo "No changes to commit"
        else
          git commit -m 'docs: update README.md'
          git push origin main
        fi

        git clone "https://${{ secrets.GITHUB_TOKEN }}@github.com/FreePhoenix888/generate-help-of-cli-apps-in-markdown-format.wiki.git"
        cp --force README.md generate-help-of-cli-apps-in-markdown-format.wiki/Home.md
        cd generate-help-of-cli-apps-in-markdown-format.wiki
        git add Home.md
        if git diff --staged --quiet
        then
          echo "No changes to commit"
        else
          git commit -m 'docs: update Home.md'
          git push
        fi
        
        npx --yes typedoc ./src/main.ts
